# -*- coding: utf-8 -*-
"""chord_recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBnh6pPX1txBdHV4rKVF0MneahBG9YiV
"""

import numpy as np
import librosa
import librosa.display
import matplotlib.pyplot as plt

# ==========================================
# 1. SYNTHESIZE THE AUDIO
# ==========================================
SAMPLE_RATE = 22050
DURATION = 1.0  # seconds per chord
t = np.linspace(0, DURATION, int(SAMPLE_RATE * DURATION), endpoint=False)

# Frequencies for our chords (Root position)
chords_freqs = {
    'C_Maj': [261.63, 329.63, 392.00], # C4, E4, G4
    'G_Maj': [196.00, 246.94, 293.66], # G3, B3, D4
    'A_Min': [220.00, 261.63, 329.63], # A3, C4, E4
    'F_Maj': [174.61, 220.00, 261.63]  # F3, A3, C4
}

progression = ['C_Maj', 'G_Maj', 'A_Min', 'F_Maj']
audio_signal = np.array([])

print("Synthesizing audio...")
for chord in progression:
    # Generate sine waves for each note in the triad
    chord_wave = sum(np.sin(2 * np.pi * f * t) for f in chords_freqs[chord])
    audio_signal = np.concatenate((audio_signal, chord_wave / 3.0))

# Add a little bit of noise to simulate real-world imperfection
audio_signal += np.random.normal(0, 0.05, len(audio_signal))

# ==========================================
# 2. EXTRACT CHROMA FEATURES
# ==========================================
print("Extracting chroma features...")
# librosa.feature.chroma_stft automatically folds the entire frequency spectrum
# into 12 distinct pitch classes (C, C#, D, etc.)
chromagram = librosa.feature.chroma_stft(y=audio_signal, sr=SAMPLE_RATE, n_fft=4096, hop_length=1024)

# ==========================================
# 3. BUILD CHORD TEMPLATES
# ==========================================
# Define 24 templates (12 Major, 12 Minor)
# Pitch classes: C=0, C#=1, D=2, D#=3, E=4, F=5, F#=6, G=7, G#=8, A=9, A#=10, B=11

templates = []
chord_labels = []
pitch_classes = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']

for i in range(12):
    # Major Triad: Root (0), Major 3rd (+4), Perfect 5th (+7)
    template_maj = np.zeros(12)
    template_maj[i] = 1
    template_maj[(i + 4) % 12] = 1
    template_maj[(i + 7) % 12] = 1
    templates.append(template_maj)
    chord_labels.append(f"{pitch_classes[i]} Maj")

    # Minor Triad: Root (0), Minor 3rd (+3), Perfect 5th (+7)
    template_min = np.zeros(12)
    template_min[i] = 1
    template_min[(i + 3) % 12] = 1
    template_min[(i + 7) % 12] = 1
    templates.append(template_min)
    chord_labels.append(f"{pitch_classes[i]} Min")

# Convert templates to a matrix (24 rows, 12 columns)
template_matrix = np.array(templates)

# ==========================================
# 4. TEMPLATE MATCHING (CHORD RECOGNITION)
# ==========================================
print("Running template-based pattern matching...")
# Compute the dot product between our 24 templates and every time frame of the chromagram.
# This gives a similarity score for every chord at every moment in time
chord_similarity = np.dot(template_matrix, chromagram)

# Find the index of the template with the highest score for each frame
predicted_chord_indices = np.argmax(chord_similarity, axis=0)

# ==========================================
# 5. PLOTTING THE RESULTS
# ==========================================
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), sharex=True)

# Graph A: The Chromagram
img1 = librosa.display.specshow(chromagram, y_axis='chroma', x_axis='time',
                                sr=SAMPLE_RATE, hop_length=1024, ax=ax1, cmap='coolwarm')
ax1.set_title('(A) Extracted Chroma Features (12 Pitch Classes)')
fig.colorbar(img1, ax=ax1, label='Energy')

# Add visual markers for the actual chord changes
for i in range(1, len(progression)):
    ax1.axvline(x=i * DURATION, color='black', linestyle='--', linewidth=2)

# Graph B: The Template Matching Output
# Plot the recognized chord over time
times = librosa.frames_to_time(np.arange(chromagram.shape[1]), sr=SAMPLE_RATE, hop_length=1024)
predicted_labels = [chord_labels[idx] for idx in predicted_chord_indices]

# Scatter plot of the predictions
ax2.scatter(times, predicted_labels, color='darkred', s=10)
ax2.set_title('(B) Predicted Chords via Template Matching')
ax2.set_xlabel('Time (seconds)')
ax2.set_ylabel('Chord')
ax2.grid(True, alpha=0.5)

# Limit the Y-axis to only show the chords that were actually detected to keep the graph clean
detected_unique_chords = list(set(predicted_labels))
ax2.set_yticks(detected_unique_chords)

# Add visual markers for the actual chord changes
for i in range(1, len(progression)):
    ax2.axvline(x=i * DURATION, color='gray', linestyle='--', linewidth=2)

plt.tight_layout()
plt.show()