# -*- coding: utf-8 -*-
"""Tempo&Beat_Tracking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wzwv71_yMsAX1ZZTxx96aLOSjSznyJ68
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import stft

# 1. Setup Parameters & Synthesize Audio
SAMPLE_RATE = 44100
DURATION = 3.0
t = np.linspace(0, DURATION, int(SAMPLE_RATE * DURATION), endpoint=False)

# Synthesize a continuous tone (flute-like) with percussive noise bursts (drum hits)
clean_tone = 0.5 * np.sin(2 * np.pi * 440 * t)
noise_bursts = np.zeros_like(t)

# Add transients at 0.5s, 1.5s, and 2.5s
for onset_time in [0.5, 1.5, 2.5]:
    idx = int(onset_time * SAMPLE_RATE)
    # 50ms burst of noise
    noise_bursts[idx:idx+int(SAMPLE_RATE*0.05)] = np.random.normal(0, 1, int(SAMPLE_RATE*0.05)) * np.linspace(1, 0, int(SAMPLE_RATE*0.05))

audio_signal = clean_tone + noise_bursts

# 2. Compute Short-Time Fourier Transform (STFT)
WINDOW_SIZE = 1024
HOP_SIZE = 256
f, t_frames, Zxx = stft(audio_signal, fs=SAMPLE_RATE, nperseg=WINDOW_SIZE, noverlap=WINDOW_SIZE-HOP_SIZE)

# Get Magnitude and Phase
mag = np.abs(Zxx)
phase = np.angle(Zxx)

# 3. Compute Novelty Functions

# --- Energy-Based Novelty ---
# Sum of squared magnitudes in each frame
energy = np.sum(mag**2, axis=0)
# Derivative of energy (half-wave rectified to only keep increases)
energy_novelty = np.diff(energy, prepend=energy[0])
energy_novelty[energy_novelty < 0] = 0

# --- Spectral-Based Novelty ---
# Logarithmic compression to balance loud and quiet frequencies
log_mag = np.log(1 + 10 * mag)
# Compute spectral difference between adjacent frames
spectral_diff = np.diff(log_mag, axis=1, prepend=log_mag[:, 0:1])
# Half-wave rectify (only keep positive changes indicating new energy)
spectral_diff[spectral_diff < 0] = 0
spectral_novelty = np.sum(spectral_diff, axis=0)

# --- Phase-Based Novelty ---
# Calculate the second derivative of the phase (phase acceleration)
# Wrap the phase to the interval [-pi, pi]
def wrap_phase(p):
    return (p + np.pi) % (2 * np.pi) - np.pi

phase_diff1 = wrap_phase(np.diff(phase, axis=1, prepend=phase[:, 0:1]))
phase_diff2 = wrap_phase(np.diff(phase_diff1, axis=1, prepend=phase_diff1[:, 0:1]))

# The novelty is the sum of the absolute phase disturbances
phase_novelty = np.sum(np.abs(phase_diff2), axis=0)

# 4. Plotting
fig, axs = plt.subplots(4, 1, figsize=(10, 8), sharex=True)
axs[0].plot(t, audio_signal, color='gray')
axs[0].set_title("Original Audio Signal")
axs[0].set_xlabel("Time (Seconds)")
axs[0].set_ylabel("Amplitude")

axs[1].plot(t_frames, energy_novelty, color='darkred')
axs[1].set_title("Energy-Based Novelty")
axs[1].set_xlabel("Time (Seconds)")
axs[1].set_ylabel("Novelty")

axs[2].plot(t_frames, spectral_novelty, color='darkblue')
axs[2].set_title("Spectral-Based Novelty")
axs[2].set_xlabel("Time (Seconds)")
axs[2].set_ylabel("Novelty")

axs[3].plot(t_frames, phase_novelty, color='darkgreen')
axs[3].set_title("Phase-Based Novelty")
axs[3].set_xlabel("Time (Seconds)")
axs[3].set_ylabel("Novelty")

# Adjust the spacing between subplots
plt.subplots_adjust(hspace=0.5)

plt.tight_layout()
plt.show()